name: 'Package and Push Helm Chart to Harbor'
description: 'Package Helm chart and push it to Harbor'

inputs:
  harbor_username:
    description: 'Username for Harbor'
    required: true
  harbor_password:
    description: 'Password for Harbor'
    required: true
  harbor_ip:
    description: 'IP address or domain of Harbor'
    required: true
  chart_directory:
    description: 'Path to the chart directory'
    required: true
  chart_name:
    description: 'Name of the Helm chart'
    required: true

runs:
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      shell: bash

    - name: Login to Harbor
      run: |
        helm registry login ${{ inputs.harbor_ip }} --username ${{ inputs.harbor_username }} --password ${{ inputs.harbor_password }}
      shell: bash

    - name: Package Helm Chart
      run: |
        helm package ${{ inputs.chart_name }}
      working-directory: ${{ inputs.chart_directory }}
      shell: bash

    - name: Push Helm Chart to Harbor
      run: |
        helm push $(ls ${inputs.chart_name}-*.tgz) oci://${{ inputs.harbor_ip }}/${{ inputs.harbor_username }}
      working-directory: ${{ inputs.chart_directory }}
      shell: bash
