name: Main Deployment Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: runner-stemdo-labs


    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up script permissions
        run: |
          chmod +x ./extract_version.sh
          chmod +x ./upload_version.sh

      - name: Extract and increment version
        id: extract_version
        run: |
          NEW_VERSION=$(./extract_version.sh)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Upload version into file
        run: |
          ./upload_version.sh "$NEW_VERSION"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_NAME }}/myapp-backend:${{ env.NEW_VERSION }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install backend ./charts/backend \
          --namespace default \
          --set image.repository=${{ secrets.ACR_NAME }}/myapp-backend \
          --set image.tag=${{ env.NEW_VERSION }} \
          --set acr.username=${{ secrets.HARBOR_USER }} \
          --set acr.password=${{ secrets.HARBOR_PASS }} \
          --set acr.server=${{ secrets.HARBOR_IP }} \
          --set acr.secretName=${{ secrets.ACR_SECRET_NAME }} \
          --set aks.clusterName=${{ secrets.AKS_NAME }} \
          --set aks.resourceGroup=${{ secrets.RESOURCE_GROUP_NAME }} \
          --set database.name=${{ secrets.DB_NAME }} \
          --set database.password=${{ secrets.DB_PASSWORD }} \
          --set database.port=${{ secrets.DB_PORT }} \
          --set database.user=${{ secrets.DB_USER }} \
          --set database.host=${{ secrets.DB_HOST }} \
          --set acr.email=${{ secrets.ACR_EMAIL }}
